name: Repository Dispatch Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  repository_dispatch:
    types: [ release ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out production code
        uses: actions/checkout@v4
      - run: |
          git checkout production
          git merge ${{ github.event.client_payload.gitRef }}
          git push
  